const images = {

  overlay: require('../Images/overlay.png'),
  add: require('../Images/add.png'),
  date: require('../Images/date.png'),
  date_copy: require('../Images/date-copy.png'),
  car: require('../Images/car.png'),
  car1: require('../Images/car1.png'),
  van: require('../Images/van.png'),
  van1: require('../Images/van1.png'),
  truck: require('../Images/truck.png'),
  truck1: require('../Images/truck1.png'),
  bg1: require('../Images/bg1.png'),
  Tapbg: require('../Images/Tapbg.png'),
  home: require('../Images/home.png'),
  msg: require('../Images/msg.gif'),
  addButton: require('../Images/addButton.png'),
  reserved: require('../Images/reserved.png'),
  open: require('../Images/open.png'),
  closed: require('../Images/closed.png'),
  Tooltip: require('../Images/TOOLTIP.png'),
  Toolbut: require('../Images/toolbut.png'),
  facebook: require('../Images/facebook.png'),
  google: require('../Images/google.png'),
  LOGIN: require('../Images/LOGIN.png'),
  SINGUP: require('../Images/SIGNUP.png'),
  SINGUP1: require('../Images/SIGNUP1.png'),
  signbg: require('../Images/signbg.png'),
  underline: require('../Images/underline.png'),
  CONTINUE: require('../Images/CONTINUE.png'),
  devide: require('../Images/divide.png'),
  libphoto: require('../Images/libphoto.png'),
  takepicture: require('../Images/takepicture.png'),
  deliverBG: require('../Images/deliverBG.png'),
  setButton: require('../Images/setButton.png'),
  modalBg: require('../Images/modalBg.png'),
  closeLock: require('../Images/closeLock.png'),
  openLock: require('../Images/openLock.png'),
  sideMenuClose: require('../Images/close.png'),
  donationIcon: require('../Images/donation.png'),
  impactIcon: require('../Images/impact.png'),
  profileIcon: require('../Images/profile.png'),
  notificationIcon: require('../Images/notification.png'),
  logoutIcon: require('../Images/logout.png'),
  whiteNot: require('../Images/not.png'),
  menuList: require('../Images/list.png'),
  home2: require('../Images/home2.png'),
  focus: require('../Images/focus.png'),
  btnClose: require('../Images/btnClose.png'),
  btnContact: require('../Images/btnContact.png'),
  btnContact1: require('../Images/btnContact1.png'),
  btnSwitchOff: require('../Images/btnSwitch.png'),
  btnSwitchOn: require('../Images/btnSwitch1.png'),
  rectangle: require('../Images/rectangle.png'),
  starFilled: require('../Images/star_filled.png'),
  starUnfilled: require('../Images/star_unfilled.png'),
  car2: require('../Images/car2.png'),
  apple: require('../Images/apple.png'),
  foodboxes: require('../Images/foodboxes.png'),
  btnCall: require('../Images/btnCall.png'),
  btnMessage: require('../Images/btnMessage.png'),
  btnReport: require('../Images/btnReport.png'),
  adrianImg: require('../Images/adrianImg.png'),
  markPostIcon: require('../Images/post.png'),
  postIcon: require('../Images/pBack.png'),
  bgImage: require('../Images/modalBg.png'),
  grayVan: require('../Images/grayVan.png'),
  duplicate: require('../Images/duplicate.png'),
  greenLock: require('../Images/greenLock.png'),
  cLock: require('../Images/cLock.png'),
  upArrow: require('../Images/upArrow.png'),
  downArrow: require('../Images/downArrow.png'),
  fDonationheader: require('../Images/fDonationheader.png'),
  fDbar: require('../Images/fDbar.png'),
  fDsearch: require('../Images/fDsearch.png'),
  fDowal: require('../Images/Oval.png'),
  fDmessage: require('../Images/fDMesage.png'),
  triangle: require('../Images/triangle.png'),
  wCarRedBack: require('../Images/WhiteCarRedBack.png'),
  wVanRedBack: require('../Images/WhiteVanRedBack.png'),
  donaterName: require('../Images/donaterName.png'),
  marker: require('../Images/marker.png'),
  close: require('../Images/close.png'),
  orangeLock: require('../Images/orangeCloseLock.png'),
  redOpenLock: require('../Images/redOpenLock.png'),
  callIcon: require('../Images/callIcon.png'),
  backIcon: require('../Images/backIcon.png'),
  cancelIcon: require('../Images/cancelIcon.png'),
  foodBoxes: require('../Images/foodboxes.png'),
  flagIcon: require('../Images/flagIcon.png'),
  bgcircle: require('../Images/bg-circle.png'),
  listingbg: require('../Images/listing-bg.png'),
  profilebg1: require('../Images/profile-bg.png'),
  profilebg2: require('../Images/profile-bg2.png'),
  call: require('../Images/call.png'),
  flag: require('../Images/flag.png'),
  msg: require('../Images/msg.png'),
  reactAngleModelBg: require('../Images/reactAngleModelBg.png'),
  orangeBack: require('../Images/orangeBack.png'),
  mHeder: require('../Images/mHeder.png'),
  sendButton: require('../Images/sendButton.png'),
  avatar: require('../Images/avatar.png'),
  clockIcon: require('../Images/clock_icon.png'),
  checked: require('../Images/checked.png'),
  unchecked: require('../Images/unchecked.png'),
  trashIcon : require('../Images/trash_icon.png'),
  cameraIcon : require('../Images/camera.png'),
  plusIcon : require('../Images/plusIcon.png'),
  popScrIcon: require('../Images/popScrIcon.png'),




}

export default images
