const images = {

  overlay: require('../Images/overlay.png'),
  add: require('../Images/add.png'),
  data: require('../Images/date.png'),
  data_copy: require('../Images/date-copy.png'),
  car: require('../Images/car.png'),
  car1: require('../Images/car1.png'),
  van: require('../Images/van.png'),
  van1: require('../Images/van1.png'),
  truck: require('../Images/truck.png'),
  truck1: require('../Images/truck1.png'),
  bg1: require('../Images/bg1.png'),
  Tapbg: require('../Images/Tapbg.png'),
  home: require('../Images/home.png'),
  msg: require('../Images/msg.gif'),
  addButton: require('../Images/addButton.png'),
  reserved: require('../Images/reserved.png'),
  open: require('../Images/open.png'),
  closed: require('../Images/closed.png'),
  Tooltip: require('../Images/TOOLTIP.png'),
  Toolbut: require('../Images/toolbut.png'),
  facebook: require('../Images/facebook.png'),
  google: require('../Images/google.png'),
  LOGIN: require('../Images/LOGIN.png'),
  SINGUP: require('../Images/SIGNUP.png'),
  SINGUP1: require('../Images/SIGNUP1.png'),
  signbg: require('../Images/signbg.png'),
  underline: require('../Images/underline.png'),
  CONTINUE: require('../Images/CONTINUE.png'),
  devide: require('../Images/divide.png'),
  libphoto: require('../Images/libphoto.png'),
  takepicture: require('../Images/takepicture.png'),
  modalBg: require('../Images/modalBg.png'),
  closeLock: require('../Images/closeLock.png'),
  openLock: require('../Images/openLock.png'),
  sideMenuClose: require('../Images/close.png'),
  donationIcon: require('../Images/donation.png'),
  impactIcon: require('../Images/impact.png'),
  profileIcon: require('../Images/profile.png'),
  notificationIcon: require('../Images/notification.png'),
  logoutIcon: require('../Images/logout.png'),
  whiteNot: require('../Images/not.png'),
  menuList: require('../Images/list.png'),
  markPostIcon: require('../Images/post.png'),
  postIcon: require('../Images/pBack.png'),
  bgImage: require('../Images/modalBg.png'),
  grayVan: require('../Images/grayVan.png'),
  duplicate: require('../Images/duplicate.png'),
  greenLock: require('../Images/greenLock.png'),
  cLock: require('../Images/cLock.png'),
  upArrow: require('../Images/upArrow.png'),
  downArrow: require('../Images/downArrow.png'),

}

export default images
