const images = {

  overlay: require('../Images/overlay.png'),
  add: require('../Images/add.png'),
  date: require('../Images/date.png'),
  date_copy: require('../Images/date-copy.png'),
  car: require('../Images/car.png'),
  car1: require('../Images/car1.png'),
  van: require('../Images/van.png'),
  van1: require('../Images/van1.png'),
  truck: require('../Images/truck.png'),
  truck1: require('../Images/truck1.png'),
  bg1: require('../Images/bg1.png'),
  Tapbg: require('../Images/Tapbg.png'),
  home: require('../Images/home.png'),
  msg: require('../Images/msg.gif'),
  addButton: require('../Images/addButton.png'),
  reserved: require('../Images/reserved.png'),
  open: require('../Images/open.png'),
  closed: require('../Images/closed.png'),
  Tooltip: require('../Images/TOOLTIP.png'),
  Toolbut: require('../Images/toolbut.png'),
  facebook: require('../Images/facebook.png'),
  google: require('../Images/google.png'),
  LOGIN: require('../Images/LOGIN.png'),
  SINGUP: require('../Images/SIGNUP.png'),
  SINGUP1: require('../Images/SIGNUP1.png'),
  signbg: require('../Images/signbg.png'),
  underline: require('../Images/underline.png'),
  CONTINUE: require('../Images/CONTINUE.png'),
  devide: require('../Images/divide.png'),
  libphoto: require('../Images/libphoto.png'),
  takepicture: require('../Images/takepicture.png'),
  deliverBG: require('../Images/deliverBG.png'),
  setButton: require('../Images/setButton.png'),
  modalBg: require('../Images/modalBg.png'),
  closeLock: require('../Images/closeLock.png'),
  openLock: require('../Images/openLock.png'),
  sideMenuClose: require('../Images/close.png'),
  donationIcon: require('../Images/donation.png'),
  impactIcon: require('../Images/impact.png'),
  profileIcon: require('../Images/profile.png'),
  notificationIcon: require('../Images/notification.png'),
  logoutIcon: require('../Images/logout.png'),
  whiteNot: require('../Images/not.png'),
  menuList: require('../Images/list.png'),
  home2: require('../Images/home2.png'),
  focus: require('../Images/focus.png'),
  btnClose: require('../Images/btnClose.png'),
  btnContact: require('../Images/btnContact.png'),
  btnContact1: require('../Images/btnContact1.png'),
  btnSwitchOff: require('../Images/btnSwitch.png'),
  btnSwitchOn: require('../Images/btnSwitch1.png'),
  rectangle: require('../Images/rectangle.png'),
  starFilled: require('../Images/star_filled.png'),
  starUnfilled: require('../Images/star_unfilled.png'),
  car2: require('../Images/car2.png'),
  apple: require('../Images/apple.png'),
  foodboxes: require('../Images/foodboxes.png'),
  btnCall: require('../Images/btnCall.png'),
  btnMessage: require('../Images/btnMessage.png'),
  btnReport: require('../Images/btnReport.png'),
  adrianImg: require('../Images/adrianImg.png'),
  markPostIcon: require('../Images/post.png'),
  postIcon: require('../Images/pBack.png'),
  bgImage: require('../Images/modalBg.png'),
  grayVan: require('../Images/grayVan.png'),
  duplicate: require('../Images/duplicate.png'),
  greenLock: require('../Images/greenLock.png'),
  cLock: require('../Images/cLock.png'),
  upArrow: require('../Images/upArrow.png'),
  downArrow: require('../Images/downArrow.png'),
  fDonationheader: require('../Images/fDonationheader.png'),
  fDbar: require('../Images/fDbar.png'),
  fDsearch: require('../Images/fDsearch.png'),
  fDowal: require('../Images/Oval.png'),
  fDmessage: require('../Images/fDMesage.png'),
  triangle: require('../Images/triangle.png'),
  wCarRedBack: require('../Images/WhiteCarRedBack.png'),
  wVanRedBack: require('../Images/WhiteVanRedBack.png'),
  donaterName: require('../Images/donaterName.png'),
  marker: require('../Images/marker.png'),
  close: require('../Images/close.png'),
  orangeLock: require('../Images/orangeCloseLock.png'),
  redOpenLock: require('../Images/redOpenLock.png'),
  callIcon: require('../Images/callIcon.png'),
  backIcon: require('../Images/backIcon.png'),
  cancelIcon: require('../Images/cancelIcon.png'),
  foodBoxes: require('../Images/foodboxes.png'),
  flagIcon: require('../Images/flagIcon.png'),
  bgcircle: require('../Images/bg-circle.png'),
  listingbg: require('../Images/listing-bg.png'),
  profilebg1: require('../Images/profile-bg.png'),
  profilebg2: require('../Images/profile-bg2.png'),
  call: require('../Images/call.png'),
  flag: require('../Images/flag.png'),
  msg: require('../Images/msg.png'),
  reactAngleModelBg: require('../Images/reactAngleModelBg.png'),
  orangeBack: require('../Images/orangeBack.png'),
  mHeder: require('../Images/mHeder.png'),
  sendButton: require('../Images/sendButton.png'),
  avatar: require('../Images/avatar.png'),
  clockIcon: require('../Images/clock_icon.png'),
  checked: require('../Images/checked.png'),
  unchecked: require('../Images/unchecked.png'),
  trashIcon : require('../Images/trash_icon.png'),
  cameraIcon : require('../Images/camera.png'),
  plusIcon : require('../Images/plusIcon.png'),
  logoBig : require('../Images/logo_big.png'),
  tipIcon : require('../Images/tipIcon.png'),
  popScrIcon: require('../Images/popScrIcon.png'),
  menuIcon: require('../Images/menuIcon.png'),
  foodboxes1: require('../Images/foodboxes1.png'),
  ic_chevron_right: require('../Images/ic_chevron_right.png'),
  back_new : require('../Images/back_new.png'),
  gradient_bg : require('../Images/background.png'),
  stars : require('../Images/Stars.png'),
  apple : require('../Images/apple.png'),
  vehicle : require('../Images/vehicle.png'),
  search_small : require('../Images/search_small.png'),
  key : require('../Images/key.png'),
  createdBy: require('../Images/createdBy.png'),
  get_bg: require('../Images/get_bg.png'),
  pin: require('../Images/pin.png'),


  rightArraw: require('../Images/rightArrow.png'),
  questionMark: require('../Images/questionMark.png'),
  deliver: require('../Images/deliver.png'),
  deliver_sel: require('../Images/deliver-sel.png'),
  non_perishable_new: require('../Images/non-perishable-new.png'),
  non_perishable_new_sel: require('../Images/non-perishable-new-sel.png'),
  paid_pickup: require('../Images/paid-pickup.png'),
  paid_pickup_sel: require('../Images/paid-picjup-sel.png'),
  perishable_new: require('../Images/perishable-new.png'),
  perishable_new_sel: require('../Images/perishable-new-sel.png'),
  prepared: require('../Images/prepared.png'),
  prepared_sel: require('../Images/prepared-sel.png'),
  voulunteer_heart: require('../Images/volunteer-heart.png'),
  voulunteer_heart_sel: require('../Images/volunteer-heart-sel.png'),
  cameraIcon: require('../Images/cameraIcon.png'),
  dateIcon: require('../Images/dateIcon.png'),
  groceriesIcon: require('../Images/groceriesIcon.png'),
  rescue_bg: require('../Images/rescue_bg.png'),
  volunteer: require('../Images/volunteer.png'),
  helpicon: require('../Images/helpicon.png'),
  deliver_guy: require('../Images/delivery-guy.png'),
  statusModal_bg: require('../Images/statusModal_bg.png'),
  pinception: require('../Images/Pinception.png'),
  food: require('../Images/Food.png'),
  oval1: require('../Images/oval1.png'),
  food_donated: require('../Images/Food_Donated.png'),
  People_Served: require('../Images/People_Served.png'),
  Global_Impact: require('../Images/Global_Impact.png'),
  date_smallIcon: require('../Images/date_smallIcon.png'),
  location_sel: require('../Images/location-sel.png'),
  location_n: require('../Images/location_n.png'),
  location: require('../Images/location.png'),

  viewListingHeader: require('../Images/viewListingHeader.png'),
  car_black: require('../Images/car_black.png'),
  pin_green: require('../Images/pin_green.png'),
  pin_blue: require('../Images/pin_blue.png'),
  pin_orange: require('../Images/pin_orange.png'),
  close_blue: require('../Images/close_blue.png'),

  clock_icon_start: require('../Images/clock_icon-start.png'),
  clock_icon_end: require('../Images/clock_icon-end.png'),
  arrow_right: require('../Images/arrow_right.png'),
  arrow_left: require('../Images/arrow_left.png'),
  plus: require('../Images/plus.png'),
  hand_shake: require('../Images/hand-shake.png'),
  popup_bg: require('../Images/popup-bg.png'),
  plus_1: require('../Images/plus-1.png'),

  donate_excess_food: require('../Images/donate_excess_food.png'),
  feed_community: require('../Images/feed_community.png'),




  add_blue: require('../Images/CompleteDonation/add_blue.png'),
  arrow_45: require('../Images/CompleteDonation/arrow_45.png'),
  calendar: require('../Images/CompleteDonation/calendar.png'),
  camera_bg: require('../Images/CompleteDonation/calendar.png'),
  camera_full: require('../Images/CompleteDonation/camera_full.png'),
  circle_ring: require('../Images/CompleteDonation/circle_ring.png'),
  complete_donation_top_bg: require('../Images/CompleteDonation/complete_donation_top_bg.png'),
  deliver_gray: require('../Images/CompleteDonation/deliver_gray.png'),
  deliver_black: require('../Images/CompleteDonation/deliver_black.png'),
  done: require('../Images/CompleteDonation/done.png'),
  location_gray: require('../Images/CompleteDonation/location_gray.png'),
  navigate: require('../Images/CompleteDonation/navigate.png'),
  nonperishable_gray: require('../Images/CompleteDonation/nonperishable_gray.png'),
  paid_pickup_gray: require('../Images/CompleteDonation/paid_pickup_gray.png'),
  paid_pickup_black: require('../Images/CompleteDonation/paid_pickup_black.png'),
  perishable_gray: require('../Images/CompleteDonation/perishable_gray.png'),
  perishable_black: require('../Images/CompleteDonation/perishable_black.png'),
  prepared_gray: require('../Images/CompleteDonation/prepared_gray.png'),
  prepared_black: require('../Images/CompleteDonation/prepared_black.png'),    
  skip: require('../Images/CompleteDonation/skip.png'),
  status_full: require('../Images/CompleteDonation/status_full.png'),
  status_left: require('../Images/CompleteDonation/status_left.png'),
  status_right: require('../Images/CompleteDonation/status_right.png'),
  timeline: require('../Images/CompleteDonation/timeline.png'),
  volunteer_gray: require('../Images/CompleteDonation/volunteer_gray.png'),
  volunteer_black: require('../Images/CompleteDonation/volunteer_black.png'),

}
export default images
