# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DonateApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'

  # Pods for DonateApp

  target 'DonateAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DonateApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DonateApp-tvOS

  target 'DonateApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
